apiVersion: v1 
stringData:
  username: mcianci2024
  passoword: ${GIT_PAT}
  project: gitops
  type: git
  url: https://github.com/Platform-Engineer-DA/gitops.git
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repository-gitops
  namespace: argocd
type: Opaque   
