apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

images:
- name: myapp
  newName: marcoscianci/gitops
  newTag: dev_17786680663
  newName: marcoscianci/gitops
  newTag: dev_17786360950

namePrefix: gitops-
nameSuffix: -dev
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: gitops
    app.kubernetes.io/name: gitops
    

patches:
- path: patch-host.yml
- path: patch-rollouts-labels.yml
