apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources: 
  - ../../base 

images:  
  - name: marcoscianci/gitops
    newTag: DEV_placeholder

namePrefix: gitops-

labels:
  - pairs:
      app: gitops          # <-- novo valor (antes era "myapp")
      app.kubernetes.io/name: gitops  # (opcional) padroniza label canonical
    includeSelectors: true
    includeTemplates: true

patchesStrategicMerge:
  - patch-host.yml   

configuration: 
 - kustomize-nameref-rollouts.yml
  