apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

images:
- name: marcoscianci/gitops
  newName: marcoscianci/gitops
  newTag: dev_17790442754
- name: myapp
  newName: marcoscianci/gitops
  newTag: dev_17787007386

namePrefix: gitops-
nameSuffix: -dev
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: gitops
    app.kubernetes.io/name: gitops
    

patches:
- path: patch-host.yml
- path: patch-rollouts-labels.yml
