apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources: 
  - ../../base 

images:  
  - name: marcoscianci/gitops
    newTag: dev_placeholder

namePrefix: gitops-
nameSuffix: -dev
labels:
  - pairs:
      app: gitops          # <-- novo valor (antes era "myapp")
      app.kubernetes.io/name: gitops  # (opcional) padroniza label canonical
    includeSelectors: true
    includeTemplates: true
    

patches:
  - path: patch-host.yml
  - path: patch-rollouts-labels.yml   

# configurations: 
#   - kustomize-nameref-rollouts.yml

