apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout      # nome do base!
spec:
  selector:
    matchLabels:
      app: gitops
      app.kubernetes.io/name: gitops
  template:
    metadata:
      labels:
        app: gitops
        app.kubernetes.io/name: gitops
