name: Workflow GitOp CD

on: 
  workflow_run:
    workflows: ["Workflow GitOp CI"]
    types: [ completed ]
    branches : [ main ]

env:
  PROJECT_NAME: "gitops"
  
jobs: 

    CD:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}        
        runs-on: ubuntu-latest
        permissions:
          contents: read

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: ArgoCD Project Sync
          uses: Platform-Engineer-DA/central-ci-cd/.github/actions/cd/argocd/oci_deploy@main
          with:
            OCI_TENANCY_OCID:   ${{ secrets.OCI_TENANCY_OCID }}
            OCI_USER_OCID:      ${{ secrets.OCI_USER_OCID }}
            OCI_FINGERPRINT:    ${{ secrets.OCI_FINGERPRINT }}
            OCI_REGION:         ${{ secrets.OCI_REGION }}
            OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
            OKE_CLUSTER_OCID:   ${{ secrets.OKE_CLUSTER_OCID }}
            GIT_PAT:            ${{ secrets.GIT_PAT }}
            ENV:              "dev" 