name: Workflow GitOps CD

on: 
    workflow_run:
        workflows: ["Workflow GitOps CI"]
        types:
            - completed

env:
    TAG_VERSION: "dev_${{ github.run_id }}"
    PROJECT_NAME: "gitops"

jobs: 
    CD:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          uses: Platform-Engineer-DA/central-ci-cd/.github/actions/ci/common/build_image@main
          with:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            PROJECT_NAME: ${{ env.PROJECT_NAME }}
            TAG_VERSION: ${{ env.TAG_VERSION }}
            

