name: Continous Integration Workflow

on: [push]

jobs: 

    CI:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Go
          uses: Platform-Engineer-DA/central-ci-cd/.github/actions/ci/golang/setup@main

        - name: Unit Test
          uses: Platform-Engineer-DA/central-ci-cd/.github/actions/ci/golang/test@main

    CD:
        runs-on: ubuntu-latest
        needs: CI

        steps:
        - name: Checkout
          uses: actions/checkout@v2


        - name: Build
          uses: Platform-Engineer-DA/central-ci-cd/.github/actions/ci/common/build_image@main
          with:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            PROJECT_NAME: "gitops"
            TAG_VERSION: ${{ github.commit.sha }}    