name: Workflow GitOp CI 

on: 
    push:
        branches: [ 'feature/**', 'hotfix/**' ]

env:
    PROJECT_NAME: "gitops"

concurrency:
    group: ci-cd-${{ github.ref }}
    cancel-in-progress: false

jobs: 

    CI:        
        runs-on: ubuntu-latest
        permissions:
            contents: read
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go
              uses: Platform-Engineer-DA/central-ci-cd/.github/actions/ci/golang/setup@main

            - name: Test
              uses: Platform-Engineer-DA/central-ci-cd/.github/actions/ci/golang/test@main
