name: Continous Integration Workflow

on: [push]

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Unit Test
          uses: mcianci2024/Platform-Engineer-DA/central-ci-cd/actions/test@main  
